@hostname = http://localhost:3000
@id = 7




###get item
GET {{hostname}}/api/geotags?latitude=49.014993&longitude=8.390049

###post item
POST {{hostname}}/api/geotags
Content-Type: application/json

{
    "name": "Test",
    "latitude": 49.02503,
    "longitude": 8.37163,
    "hashtag": "#test"
}



###get item with id
GET {{hostname}}/api/geotags/{{id}}


###put item with id
PUT  {{hostname}}/api/geotags/{{id}}
Content-Type: application/json

{
    "name": "Test",
    "latitude": 49.02503,
    "longitude": 8.37163,
    "hashtag": "#test"
}


###delete item with id
DELETE  {{hostname}}/api/geotags/{{id}}
